package org.questionBank.data;
// Generated Nov 20, 2016 10:43:21 AM by Hibernate Tools 5.2.0.Beta1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="questionbank"
)
public class Course  implements java.io.Serializable {


     private Integer id;
     private String courseName;
     private String courseNumber;
     private String deptName;
     private Integer credit;
     private Set<Person> persons = new HashSet<Person>(0);
     private Set<Question> questions = new HashSet<Question>(0);

    public Course() {
    }

    public Course(String courseName, String courseNumber, String deptName, Integer credit, Set<Person> persons, Set<Question> questions) {
       this.courseName = courseName;
       this.courseNumber = courseNumber;
       this.deptName = deptName;
       this.credit = credit;
       this.persons = persons;
       this.questions = questions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="course_name", length=64)
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    
    @Column(name="course_number", length=8)
    public String getCourseNumber() {
        return this.courseNumber;
    }
    
    public void setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber;
    }

    
    @Column(name="dept_name", length=8)
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    
    @Column(name="credit")
    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="teaches", catalog="questionbank", joinColumns = { 
        @JoinColumn(name="course_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="person_id", nullable=false, updatable=false) })
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }




}


