package org.questionBank.data;
// Generated Sep 13, 2016 2:54:40 AM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "COURSE", schema = "SYSTEM")
public class Course implements java.io.Serializable {

	private String courseId;
	private String title;
	private String deptName;
	private BigDecimal credit;
	private Set persons = new HashSet(0);
	private Set questions = new HashSet(0);

	public Course() {
	}

	public Course(String courseId) {
		this.courseId = courseId;
	}

	public Course(String courseId, String title, String deptName, BigDecimal credit, Set persons, Set questions) {
		this.courseId = courseId;
		this.title = title;
		this.deptName = deptName;
		this.credit = credit;
		this.persons = persons;
		this.questions = questions;
	}

	@Id

	@Column(name = "COURSE_ID", unique = true, nullable = false, length = 7)
	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@Column(name = "TITLE", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DEPT_NAME", length = 7)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "CREDIT", precision = 22, scale = 0)
	public BigDecimal getCredit() {
		return this.credit;
	}

	public void setCredit(BigDecimal credit) {
		this.credit = credit;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "courses")
	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set questions) {
		this.questions = questions;
	}

}
