package org.questionBank.data;
// Generated Oct 30, 2016 3:13:59 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "Course", catalog = "questionbank")
public class Course implements java.io.Serializable {

	private Integer id;
	private String courseName;
	private String courseNumber;
	private String deptName;
	private Integer credit;

	public Course() {
	}

	public Course(String courseName, String courseNumber, String deptName, Integer credit) {
		this.courseName = courseName;
		this.courseNumber = courseNumber;
		this.deptName = deptName;
		this.credit = credit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "course_name", length = 64)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "course_number", length = 4)
	public String getCourseNumber() {
		return this.courseNumber;
	}

	public void setCourseNumber(String courseNumber) {
		this.courseNumber = courseNumber;
	}

	@Column(name = "dept_name", length = 8)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "credit")
	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

}
