package org.questionBank.data;
// Generated Oct 3, 2016 12:52:41 AM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON", schema = "SYSTEM")
public class Person implements java.io.Serializable {

	private String perId;
	private String firstName;
	private String lastName;
	private String userName;
	private String password;
	private Set courses = new HashSet(0);

	public Person() {
	}

	public Person(String perId) {
		this.perId = perId;
	}

	public Person(String perId, String firstName, String lastName, String userName, String password, Set courses) {
		this.perId = perId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.userName = userName;
		this.password = password;
		this.courses = courses;
	}

	@Id

	@Column(name = "PER_ID", unique = true, nullable = false, length = 7)
	public String getPerId() {
		return this.perId;
	}

	public void setPerId(String perId) {
		this.perId = perId;
	}

	@Column(name = "FIRST_NAME", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "USER_NAME", length = 7)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "TEACHES", schema = "SYSTEM", joinColumns = {
			@JoinColumn(name = "PER_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "COURSE_ID", nullable = false, updatable = false) })
	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
