package org.questionBank.data;
// Generated Sep 13, 2016 2:54:40 AM by Hibernate Tools 5.1.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON", schema = "SYSTEM")
public class Person implements java.io.Serializable {

	private String perId;
	private String name;
	private String userName;
	private String password;
	private String aptNo;
	private String city;
	private String state;
	private BigDecimal zipCode;
	private String email;
	private Character gender;
	private Set courses = new HashSet(0);

	public Person() {
	}

	public Person(String perId) {
		this.perId = perId;
	}

	public Person(String perId, String name, String userName, String password, String aptNo, String city, String state,
			BigDecimal zipCode, String email, Character gender, Set courses) {
		this.perId = perId;
		this.name = name;
		this.userName = userName;
		this.password = password;
		this.aptNo = aptNo;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		this.email = email;
		this.gender = gender;
		this.courses = courses;
	}

	@Id

	@Column(name = "PER_ID", unique = true, nullable = false, length = 7)
	public String getPerId() {
		return this.perId;
	}

	public void setPerId(String perId) {
		this.perId = perId;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "USER_NAME", length = 7)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "APT_NO", length = 5)
	public String getAptNo() {
		return this.aptNo;
	}

	public void setAptNo(String aptNo) {
		this.aptNo = aptNo;
	}

	@Column(name = "CITY", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "ZIP_CODE", precision = 22, scale = 0)
	public BigDecimal getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(BigDecimal zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "EMAIL", length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "GENDER", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "TEACHES", schema = "SYSTEM", joinColumns = {
			@JoinColumn(name = "PER_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "COURSE_ID", nullable = false, updatable = false) })
	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
