package org.questionBank.data;
// Generated Oct 3, 2016 12:52:41 AM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "QUESTION", schema = "SYSTEM")
public class Question implements java.io.Serializable {

	private String questionId;
	private Course course;
	private String chapter;
	private Set answers = new HashSet(0);

	public Question() {
	}

	public Question(String questionId) {
		this.questionId = questionId;
	}

	public Question(String questionId, Course course, String chapter, Set answers) {
		this.questionId = questionId;
		this.course = course;
		this.chapter = chapter;
		this.answers = answers;
	}

	@Id

	@Column(name = "QUESTION_ID", unique = true, nullable = false, length = 7)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COURSE_ID")
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "CHAPTER", length = 7)
	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "question")
	public Set getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set answers) {
		this.answers = answers;
	}

}
