package org.questionBank.data;
// Generated Oct 18, 2016 9:47:48 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeachesId generated by hbm2java
 */
@Embeddable
public class TeachesId implements java.io.Serializable {

	private int perId;
	private int courseId;

	public TeachesId() {
	}

	public TeachesId(int perId, int courseId) {
		this.perId = perId;
		this.courseId = courseId;
	}

	@Column(name = "per_id", nullable = false)
	public int getPerId() {
		return this.perId;
	}

	public void setPerId(int perId) {
		this.perId = perId;
	}

	@Column(name = "course_id", nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeachesId))
			return false;
		TeachesId castOther = (TeachesId) other;

		return (this.getPerId() == castOther.getPerId()) && (this.getCourseId() == castOther.getCourseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPerId();
		result = 37 * result + this.getCourseId();
		return result;
	}

}
