/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2016-11-07 15:06:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"en\" class=\" js no-touch\">\n");
      out.write(" \n");
      out.write(" <head>\n");
      out.write("  <title>QBMS</title>\n");
      out.write("   \n");
      out.write("   <meta charset=\"utf-8\">\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("   <link rel=\"stylesheet\" href=\"IndexFiles/bootstrap.min.css\">\n");
      out.write("   <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600|Raleway:600,300|Josefin+Slab:400,700,600italic,600,400italic' rel='stylesheet' type='text/css'>\n");
      out.write("   <link href=\"IndexFiles/font-awesome.css\" rel=\"stylesheet\">\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"IndexFiles/slick.css\"/>\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"IndexFiles/slick-theme.css\"/>\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"IndexFiles/style.css\">\n");
      out.write(" </head>\n");
      out.write(" \n");
      out.write(" <body>\n");
      out.write("  <!--HEADER START-->\n");
      out.write("  <row class=\"main-navigation\">\n");
      out.write("   <nav class=\"navbar navbar-default\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t \n");
      out.write("\t <div class=\"navbar-header\">\n");
      out.write("\t  <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("\t   <span class=\"icon-bar\"></span>\n");
      out.write("\t   <span class=\"icon-bar\"></span>\n");
      out.write("\t   <span class=\"icon-bar\"></span>\n");
      out.write("\t  </button>\n");
      out.write("\t  <a class=\"navbar-brand\" href=\"index.jsp\"><i class=\"fa fa-fw fa-graduation-cap\"></i> QBMS</a>\n");
      out.write("\t </div>\n");
      out.write("\t  \n");
      out.write("\t <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("\t  <ul class=\"nav navbar-nav navbar-right\" style=\"padding-top: 5px;\">\n");
      out.write("\t   <li class=\"active\"><a href=\"index.jsp\">Home</a></li>\n");
      out.write("\t   <li><a href=\"AboutTeam.jsp\">Contact Team 'C'</a></li>\n");
      out.write("\t  </ul>\n");
      out.write("\t </div>\n");
      out.write("    </div>\n");
      out.write("   \n");
      out.write("   </nav>\n");
      out.write("  </row>\n");
      out.write("  <!--HEADER END-->\n");
      out.write("\n");
      out.write("  <!--BANNER START-->\n");
      out.write("  <div id=\"banner\" class=\"section-padding\">\n");
      out.write("   <div class=\"container\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t <div class=\"jumbotron\">\n");
      out.write("\t  <h1 class=\"small\">Welcome To <span class=\"bold\">QBMS</span></h1>\n");
      out.write("\t  <p class=\"big\">Question Bank Management System</p>\n");
      out.write("\t   <!--   <a href=\"adminlogin.jsp\" class=\"btn btn-banner\">Admin Sign In<i class=\"fa fa-send\"></i></a> -->\n");
      out.write("\t  <a href=\"teacherlogin.jsp\" class=\"btn btn-banner\">Sign In<i class=\"fa fa-send\"></i></a>\n");
      out.write("      <a href=\"teachersignup.jsp\" class=\"btn btn-banner\">Sign Up<i class=\"fa fa-send\"></i></a>\n");
      out.write("\t </div>\n");
      out.write("\t</div>\n");
      out.write("   </div>\n");
      out.write("  </div>\n");
      out.write("  <!--BANNER END-->\n");
      out.write("\n");
      out.write("  <!--CTA1 START-->\n");
      out.write("  <div class=\"cta-1\">\n");
      out.write("   <div class=\"container\">\n");
      out.write("\t<div class=\"row text-center white\">\n");
      out.write("\t <h1 class=\"cta-title\">Agile Engineering!!</h1>\n");
      out.write("\t <p class=\"cta-sub-title\">Question Bank Management System Project</p>\n");
      out.write("\t</div>\n");
      out.write("   </div>\n");
      out.write("  </div>\n");
      out.write("  <!--CTA1 END-->\n");
      out.write(" \n");
      out.write("  <!--FOOTER START-->\n");
      out.write("  <div class=\"footer-bottom\">\n");
      out.write("   <div class=\"container\">\n");
      out.write("\t<div style=\"visibility: visible; animation-name: zoomIn;\" class=\"col-md-12 text-center wow zoomIn\">\n");
      out.write("\t <div class=\"footer_copyright\">\n");
      out.write("\t <p> Copyright © Team 'C' All Rights Reserved.</p>\t\t\t\t\t\n");
      out.write("\t </div>\n");
      out.write("    </div>\n");
      out.write("   </div>\n");
      out.write("  </div>\n");
      out.write("  <!--FOOTER END--> \n");
      out.write("    \n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("  <script src=\"IndexFiles/jquery.mixitup.js\" type=\"text/javascript\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"IndexFiles/slick.min.js\"></script>\n");
      out.write("\t\n");
      out.write("  <!--for smooth scrolling-->\n");
      out.write("  <script>\n");
      out.write("\t $('a').click(\n");
      out.write("\t function()\n");
      out.write("\t {\n");
      out.write("      $('html, body').animate({ scrollTop: $( $.attr(this, 'href') ).offset().top}, 500);\n");
      out.write("      return false;\n");
      out.write("     }\n");
      out.write("     );\n");
      out.write("  </script>\n");
      out.write("  \t\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("     $(function()\n");
      out.write("     {\n");
      out.write("      // Instantiate MixItUp:\n");
      out.write("      $('#Container').mixItUp();\n");
      out.write("     });\n");
      out.write("\n");
      out.write("\t $('.autoplay').slick({\n");
      out.write("     dots: true,\n");
      out.write("     infinite: false,\n");
      out.write("     speed: 300,\n");
      out.write("     slidesToShow: 2,\n");
      out.write("     slidesToScroll: 3,\n");
      out.write("     responsive: [\n");
      out.write("     {\n");
      out.write("      breakpoint: 1024,\n");
      out.write("      settings: \n");
      out.write("      {\n");
      out.write("       slidesToShow: 3,\n");
      out.write("       slidesToScroll: 3,\n");
      out.write("       infinite: true,\n");
      out.write("       dots: true\n");
      out.write("      }\n");
      out.write("     },\n");
      out.write("     {\n");
      out.write("      breakpoint: 600,\n");
      out.write("      settings: \n");
      out.write("      {\n");
      out.write("       slidesToShow: 2,\n");
      out.write("       slidesToScroll: 2\n");
      out.write("      }\n");
      out.write("     },\n");
      out.write("     {\n");
      out.write("      breakpoint: 480,\n");
      out.write("      settings:\n");
      out.write("      {\n");
      out.write("       slidesToShow: 1,\n");
      out.write("       slidesToScroll: 1\n");
      out.write("      }\n");
      out.write("     }\n");
      out.write("\n");
      out.write("    // You can unslick at a given breakpoint now by adding:\n");
      out.write("    // settings: \"unslick\"\n");
      out.write("    // instead of a settings object\n");
      out.write("    ]\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write(" </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
