/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2016-11-07 15:06:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class teacherdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2_1.jar", Long.valueOf(1363889244000L));
    _jspx_dependants.put("jar:file:/Users/christianlevi/Desktop/schoolwork/courses/AgileSoftwareEngineering/Project/questionBank6363/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QBServer/WEB-INF/lib/jstl-1.2_1.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "SideNavigation.jsp", out, false);
      out.write(" \n");
      out.write("<html class=\"st-layout ls-top-navbar-large ls-bottom-footer show-sidebar sidebar-l3\" lang=\"en\">\n");
      out.write(" <head>\n");
      out.write("  <title>Welcome</title>\n");
      out.write("  <link href=\"TeacherDashboardFiles/all.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"TeacherDashboardFiles/app.css\" rel=\"stylesheet\">\n");
      out.write(" </head>\n");
      out.write(" <body>\n");
      out.write("  <!-- sidebar effects OUTSIDE of st-pusher: -->\n");
      out.write("  <!-- st-effect-1, st-effect-2, st-effect-4, st-effect-5, st-effect-9, st-effect-10, st-effect-11, st-effect-12, st-effect-13 -->\n");
      out.write("  <!-- content push wrapper -->\n");
      out.write("  <div class=\"st-pusher\" id=\"content\">\n");
      out.write("   <!-- sidebar effects INSIDE of st-pusher: -->\n");
      out.write("   <!-- st-effect-3, st-effect-6, st-effect-7, st-effect-8, st-effect-14 -->\n");
      out.write("   <!-- this is the wrapper for the content -->\n");
      out.write("    <div class=\"st-content\">\n");
      out.write("    <!-- extra div for emulating position:fixed of the menu -->\n");
      out.write("     <div class=\"st-content-inner padding-none\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("       \n");
      out.write("       <div class=\"page-section\">\n");
      out.write("        <h1 class=\"text-display-1\">Dashboard</h1>\n");
      out.write("       </div>\n");
      out.write("       <div class=\"row\" data-toggle=\"isotope\">\n");
      out.write("        \n");
      out.write("        <div class=\"item col-xs-12 col-lg-6\">\n");
      out.write("         <div class=\"panel panel-default paper-shadow\" data-z=\"0.5\">\n");
      out.write("          <div class=\"panel-heading\">\n");
      out.write("           <h4 class=\"text-headline margin-none\">All Courses</h4>\n");
      out.write("           <p class=\"text-subhead text-light\">Upload courses</p>\n");
      out.write("          </div>\n");
      out.write("\t      <div class=\"panel-footer\">\n");
      out.write("           <a  data-animated href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"class=\"btn btn-success paper-shadow relative\" data-z=\"0\" data-hover-z=\"1\" data-animated > View Courses</a>\n");
      out.write("          </div>\n");
      out.write("         </div>\n");
      out.write("        </div>\n");
      out.write("          \n");
      out.write("          <div class=\"item col-xs-12 col-lg-6\">\n");
      out.write("           <div class=\"panel panel-default paper-shadow\" data-z=\"0.5\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("             <h4 class=\"text-headline margin-none\">All Questions</h4>\n");
      out.write("             <p class=\"text-subhead text-light\">Upload questions </p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-footer text-right\">\n");
      out.write("             <a class=\"btn btn-success paper-shadow relative\" data-z=\"0\" data-hover-z=\"1\" data-animated href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" >View Questions</a>\n");
      out.write("            </div>\n");
      out.write("           </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("        \n");
      out.write("         </div>\n");
      out.write("        </div>\n");
      out.write("       </div>\n");
      out.write("\t  </div>\n");
      out.write("     </div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t<!--  \t<?php\n");
      out.write(" \t\t\t\t  $row_count=1;\n");
      out.write(" while ($row = mysql_fetch_array($result)) {\n");
      out.write("            if($row_count<=3){\n");
      out.write("  ?>\n");
      out.write("                  <ul class=\"list-group\">\n");
      out.write("                    <li class=\"list-group-item media v-middle\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("\t\t\t<a href=\"WEB-INF/views/courses/teachercourseview.jsp\" class=\"text-subhead list-group-link\"><?php echo $row['course_name'] ?></a>\n");
      out.write("                      </div>\n");
      out.write("     \n");
      out.write("                  </ul>\n");
      out.write("\t\t\t\t  \t       <?php\n");
      out.write("\t  }\n");
      out.write("\t  \n");
      out.write("\t  $row_count++;\n");
      out.write("\t\n");
      out.write("\t................ \t\t\t   }\n");
      out.write(" ?> -->\n");
      out.write("\t\t\t   \n");
      out.write("               \n");
      out.write("\t\t<!--  \t\t  <?php\n");
      out.write("\t\t\t\t  $row_count=1;\n");
      out.write("\t\t\t\t   while ($row = mysql_fetch_array($result1)) {\n");
      out.write("      if($row_count<=3){\n");
      out.write("  ?>\n");
      out.write("                  <ul class=\"list-group\">\n");
      out.write("                    <li class=\"list-group-item media v-middle\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h4 class=\"text-subhead margin-none\">\n");
      out.write("                          <a  class=\"list-group-link\"><?php echo $row['quiz_obj_title']?></a>\n");
      out.write("                        </h4>\n");
      out.write("                        <div class=\"caption\">\n");
      out.write("                          <span class=\"text-light\"></span>\n");
      out.write("                          <a ><?php echo $row['course_name']?></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"media-right text-center\">\n");
      out.write("                        <div class=\"text-display-12\"><?php echo $row['quiz_obj_type']?></div>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("\t\t\t\t             <?php\n");
      out.write("\t\t\t\t   }\n");
      out.write("\t\t\t\t   $row_count++;\n");
      out.write("\t\t\t\t   }\n");
      out.write("\t  \n");
      out.write("\t  \n");
      out.write(" ?>-->\n");
      out.write("   \t \t<!--    \n");
      out.write("     <div class=\"item col-xs-12 col-lg-6\" style =\"background-color: white;\">\n");
      out.write("\t \t   <h4 class=\"text-headline margin-none\">Forum Activity</h4>\n");
      out.write("\t\t   \n");
      out.write("                <p class=\"text-subhead text-light\">Latest forum topics & comments</p>\n");
      out.write("\t\t\t\t\n");
      out.write("\t      <ul class=\"list-group relative paper-shadow\" data-hover-z=\"0.5\" data-animated>\n");
      out.write("\t\t  \t  \n");
      out.write("\t\t  \t                           <li class=\"list-group-item paper-shadows\">\n");
      out.write("                    <div class=\"media v-middle\">\n");
      out.write("                      <div class=\"media-left\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <img src=\"images/<?php echo $row['user_pic']?>\" alt=\"person\" class=\"img-circle width-40\" />\n");
      out.write("                        </a>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <a href=\"forumdetail.php?uid=<?php echo $Login_id?>&utype=<?php echo 'teacher'?>&username=<?php echo $row['forum_postby']?>&userpic=<?php echo $row['user_pic']?>&forumid=<?php echo  $row['forum_id']?>&screen=<?php echo 0 ?>\" class=\"text-subhead link-text-color\"><?php echo $row['forum_question']?></a>\n");
      out.write("                        <div class=\"text-light\">\n");
      out.write("                          Topic: <a><?php echo $row['forum_title']?></a> &nbsp; By: <a><?php echo $row['forum_postby']?></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                     <div class=\"media-right\">\n");
      out.write("                        <div class=\"width-60 text-right\">\n");
      out.write("\t\t\t\t\t                          <td><?php echo $date ?></td>\n");
      out.write("                          \n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("                  </li> \n");
      out.write("\t\t\t  \t\t  \n");
      out.write("                </ul>\t\t\n");
      out.write("              </div>\n");
      out.write("\t\t-->\t  \n");
      out.write("            \n");
      out.write("        <!-- /st-content-inner -->\n");
      out.write("            <!-- /st-content-inner -->\n");
      out.write("      <!-- /st-content -->\n");
      out.write("    \n");
      out.write("    <!-- /st-pusher -->\n");
      out.write("    <!-- Footer -->\n");
      out.write("    \n");
      out.write("    <footer class=\"footer\">\n");
      out.write("      <strong>QBMS</strong>  &copy; Copyright 2016\n");
      out.write("    </footer>\n");
      out.write("    <!-- // Footer -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /teacherdashboard.jsp(35,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/TeacherCourseView");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /teacherdashboard.jsp(47,110) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/TeacherCourseView");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    }
    return false;
  }
}
