/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2016-10-23 01:01:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class teacherdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("   \n");
      out.write("\n");
      out.write("<html class=\"st-layout ls-top-navbar-large ls-bottom-footer show-sidebar sidebar-l3\" lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <meta name=\"description\" content=\"\">\n");
      out.write("  <meta name=\"author\" content=\"\">\n");
      out.write("  <title>Welcome</title>\n");
      out.write("\n");
      out.write("  \n");
      out.write("  <link href=\"TeacherDashboardFiles/all.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <link href=\"TeacherDashboardFiles/app.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!-- Wrapper required for sidebar transitions -->\n");
      out.write("  <div class=\"st-container\">\n");
      out.write("\n");
      out.write("    <!-- Fixed navbar -->\n");
      out.write("    <div class=\"navbar navbar-size-large navbar-default navbar-fixed-top\" role=\"navigation\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("          <a href=\"#sidebar-menu\" data-toggle=\"sidebar-menu\" class=\"toggle pull-left visible-xs\"><i class=\"fa fa-ellipsis-v\"></i></a>\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#main-nav\">\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("          </button>\n");
      out.write("          <div class=\"navbar-brand navbar-brand-primary navbar-brand-logo navbar-nav-padding-left\">\n");
      out.write("               &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a class=\"svg\" href=\"index.jsp\">\n");
      out.write("              <img style=\"margin-top:7px;\" alt=\"\" src=\"AdminDashboardFiles/logo.png\" >\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"main-nav\">\n");
      out.write("          <ul class=\"nav navbar-nav\">\n");
      out.write("           \n");
      out.write("          </ul>\n");
      out.write("          <ul class=\"nav navbar-nav navbar-nav-bordered navbar-right\">\n");
      out.write("            <!-- Teacher -->\n");
      out.write("             <li >\n");
      out.write("              <a >\n");
      out.write("                <i class=\"fa fa-user\" aria-hidden=\"true\"></i>\n");
      out.write("                <span class=\"badge badge-primary\">Teacher</span>\n");
      out.write("              </a>\n");
      out.write("            \n");
      out.write("            </li>\n");
      out.write("            <!-- // Teacher -->\n");
      out.write("            <!-- User -->\n");
      out.write("            <li class=\"dropdown\">\n");
      out.write("                <li><a href=\"teacherlogin.jsp\">Logout</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("        </div>\n");
      out.write("        <!-- /.navbar-collapse -->\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\t\n");
      out.write(" <!-- Sidebar component with st-effect-1 (set on the toggle button within the navbar) -->\n");
      out.write("    <div class=\"sidebar left sidebar-size-3 sidebar-offset-0 sidebar-visible-desktop sidebar-visible-mobile sidebar-skin-dark\" id=\"sidebar-menu\" data-type=\"collapse\">\n");
      out.write("      <div data-scrollable>\n");
      out.write("\n");
      out.write("        <div class=\"sidebar-block\">\n");
      out.write("          <div class=\"profile\">\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <img src=\"admin.jpg\" alt=\"people\" class=\"img-circle width-80\" />\n");
      out.write("            </a>\n");
      out.write("            <h4 class=\"text-display-1 margin-none\"><?php echo $login_session; ?></h4>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <ul class=\"sidebar-menu\">\n");
      out.write("          <li class=\"active\"><a href=\"teacherdashboard.php\"><i class=\"fa fa-bar-chart-o\"></i><span>Dashboard</span></a></li>\n");
      out.write("          <li class=\"hasSubmenu\">\n");
      out.write("            <a href=\"#course-menu\"><i class=\"fa fa-book\"></i><span>Courses</span></a>\n");
      out.write("            <ul id=\"course-menu\">\n");
      out.write("          \t\t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("\t\t\t\t<button name=\"courseview\" type=\"submit\" value=\" Course View \" class=\"btn btn-inverse\"><span>My Course</span></button></form></li>\n");
      out.write("             \t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value=\"\"/>\n");
      out.write("\t\t\t\t<button name=\"uploadlecture\" type=\"submit\" value=\" Assign Leacture \" class=\"btn btn-inverse\"><span>Upload Lecture</span></form></li>   \n");
      out.write("             \t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("\t\t\t\t<button name=\"viewlectureofcourse\" type=\"submit\" value=\" Lecture View \" class=\"btn btn-inverse\">View Lecture</span></form></li>           \t\t\t  \n");
      out.write("       \t\t</ul>\n");
      out.write("          </li>\n");
      out.write("    <li class=\"hasSubmenu\">\n");
      out.write("            <a href=\"#student-menu\"><i class=\"fa fa-user\"></i><span>Students</span></a>\n");
      out.write("            <ul id=\"student-menu\">\n");
      out.write("          <li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"studentview\" type=\"submit\" value=\" student View \" class=\"btn btn-inverse\"><span>Students View</span></button></form></li>          \t\t\t  \n");
      out.write("       </ul>\n");
      out.write("          </li>\n");
      out.write("\t\t  <li class=\"hasSubmenu\">\n");
      out.write("            <a href=\"#quiz-menu\"><i class=\"fa fa-edit\"></i><span>Quiz</span></a>         \n");
      out.write("\t\t\t<ul id=\"quiz-menu\">\n");
      out.write("\t\t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"chosecourseforquiz\" type=\"submit\" value=\"chosecourseforquiz\" class=\"btn btn-inverse\"><span>Upload Quiz</span></button></form></li>  \t\n");
      out.write("\t\t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"quizdownload\" type=\"submit\" value=\"quizdownload\" class=\"btn btn-inverse\"><span>Download Solution</span></button></form></li> \n");
      out.write("\t\t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"quizhistory\" type=\"submit\" value=\"quizhistory\" class=\"btn btn-inverse\"><span>Quiz History</span></button></form></li>  \t\n");
      out.write(" \t\t\n");
      out.write("\t\t\t </ul>\n");
      out.write("          </li>\n");
      out.write("\t\t    <li class=\"hasSubmenu\">\n");
      out.write("            <a href=\"#assignment-menu\"><i class=\"md md-assignment\"></i><span>Assignment</span></a>         \n");
      out.write("\t\t\t<ul id=\"assignment-menu\">\n");
      out.write("\t\t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"assignmentchosecourse\" type=\"submit\" value=\"chosecourseforquiz\" class=\"btn btn-inverse\"><span>Upload Assignment</span></button></form></li>  \t\n");
      out.write("\t\t\t<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"assignmenthistory\" type=\"submit\" value=\"quizhistory\" class=\"btn btn-inverse\"><span>Assignment History</span></button></form></li>  \t\t\t\t\n");
      out.write("\t\t\t </ul>\n");
      out.write("          </li>\n");
      out.write("\t\t  <li class=\"hasSubmenu\">\n");
      out.write("            <a href=\"#activity-menu\"><i class=\"fa fa-bar-chart-o\"></i><span>Student Activities</span></a>\n");
      out.write("            <ul id=\"activity-menu\">\n");
      out.write("\t\t\n");
      out.write("              <li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"LA\" type=\"submit\" value=\"lectureActivity\" class=\"btn btn-inverse\"><span>Lecture Activities</span></button></form> </li>      \n");
      out.write("  <li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"CA\" type=\"submit\" value=\"courseactivity\" class=\"btn btn-inverse\"><span>Course Activities</span></button></form> </li>      \n");
      out.write("<li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"CG\" type=\"submit\" value=\"coursegraph\" class=\"btn btn-inverse\"><span>Course Graph</span></button></form> </li>      \n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"hasSubmenu\">\n");
      out.write("            <a href=\"#forum-menu\"><i class=\"fa fa-file-text-o\"></i><span>Forum</span></a>\n");
      out.write("            <ul id=\"forum-menu\">\n");
      out.write("\t\t\n");
      out.write("              <li><form action=\"\" method=\"post\"> <input type=\"hidden\"  name=\"tid\" value= \"\"/>\n");
      out.write("<button name=\"formhome\" type=\"submit\" value=\"form\" class=\"btn btn-inverse\"><span>Forum Home</span></button></form> </li>      \n");
      out.write("  \n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"hasSubmenu\">\n");
      out.write("            <a href=\"#account-menu\"><i class=\"fa fa-user\"></i><span>Account</span></a>\n");
      out.write("            <ul id=\"account-menu\">\n");
      out.write("           <li><form action=\"\" method=\"post\">\n");
      out.write("<button name=\"editprofile\" type=\"submit\" value=\"editprofile\" class=\"btn btn-inverse\"><span>Edit Profile</span></button></form></li>\n");
      out.write("             \n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\t\t    \n");
      out.write("          <li><a  href=\"logoutt.php\" class=\"fa fa-sign-out\"></i><span>Logout</span></a></li>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- sidebar effects OUTSIDE of st-pusher: -->\n");
      out.write("    <!-- st-effect-1, st-effect-2, st-effect-4, st-effect-5, st-effect-9, st-effect-10, st-effect-11, st-effect-12, st-effect-13 -->\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("   \n");
      out.write("\n");
      out.write("    <!-- content push wrapper -->\n");
      out.write("    <div class=\"st-pusher\" id=\"content\">\n");
      out.write("\n");
      out.write("      <!-- sidebar effects INSIDE of st-pusher: -->\n");
      out.write("      <!-- st-effect-3, st-effect-6, st-effect-7, st-effect-8, st-effect-14 -->\n");
      out.write("\n");
      out.write("      <!-- this is the wrapper for the content -->\n");
      out.write("      <div class=\"st-content\">\n");
      out.write("\n");
      out.write("        <!-- extra div for emulating position:fixed of the menu -->\n");
      out.write("        <div class=\"st-content-inner padding-none\">\n");
      out.write("\n");
      out.write("         \n");
      out.write("          <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("            <div class=\"page-section\">\n");
      out.write("              <h1 class=\"text-display-1\">Dashboard</h1>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row\" data-toggle=\"isotope\">\n");
      out.write("              \n");
      out.write("              <div class=\"item col-xs-12 col-lg-6\">\n");
      out.write("                <div class=\"panel panel-default paper-shadow\" data-z=\"0.5\">\n");
      out.write("                  <div class=\"panel-heading\">\n");
      out.write("                    <h4 class=\"text-headline margin-none\">All Courses</h4>\n");
      out.write("                    <p class=\"text-subhead text-light\">Uploded courses</p>\n");
      out.write("                  </div>\n");
      out.write("\t\t\t<?php\n");
      out.write(" \t\t\t\t  $row_count=1;\n");
      out.write("\n");
      out.write(" while ($row = mysql_fetch_array($result)) {\n");
      out.write("            if($row_count<=3){\n");
      out.write("  ?>\n");
      out.write("                  <ul class=\"list-group\">\n");
      out.write("                    <li class=\"list-group-item media v-middle\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("\t\t\t<a href=\"teachercourseview.php?tid=<?php echo $Login_id?>\" class=\"text-subhead list-group-link\"><?php echo $row['course_name'] ?></a>\n");
      out.write("                      </div>\n");
      out.write("     \n");
      out.write("                  </ul>\n");
      out.write("\t\t\t\t  \t       <?php\n");
      out.write("\t  }\n");
      out.write("\t  \n");
      out.write("\t  $row_count++;\n");
      out.write("\t\t\t\t   }\n");
      out.write(" ?>\n");
      out.write("\n");
      out.write("                  <div class=\"panel-footer text-right\">\n");
      out.write("                    <a href=\"teachercourseview.php?tid=<?php echo $Login_id?>\" class=\"btn btn-success paper-shadow relative\" data-z=\"0\" data-hover-z=\"1\" data-animated>View Courses</a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\t\t\t   \n");
      out.write("\n");
      out.write("               <div class=\"item col-xs-12 col-lg-6\">\n");
      out.write("                <div class=\"panel panel-default paper-shadow\" data-z=\"0.5\">\n");
      out.write("                  <div class=\"panel-heading\">\n");
      out.write("                    <h4 class=\"text-headline margin-none\">Quizzes</h4>\n");
      out.write("                    <p class=\"text-subhead text-light\">Recently Uploaded Quiz </p>\n");
      out.write("                  </div>\n");
      out.write("\t\t\t\t  <?php\n");
      out.write("\t\t\t\t  $row_count=1;\n");
      out.write("\t\t\t\t   while ($row = mysql_fetch_array($result1)) {\n");
      out.write("      if($row_count<=3){\n");
      out.write("  ?>\n");
      out.write("                  <ul class=\"list-group\">\n");
      out.write("                    <li class=\"list-group-item media v-middle\">\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <h4 class=\"text-subhead margin-none\">\n");
      out.write("                          <a  class=\"list-group-link\"><?php echo $row['quiz_obj_title']?></a>\n");
      out.write("                        </h4>\n");
      out.write("                        <div class=\"caption\">\n");
      out.write("                          <span class=\"text-light\">Course:</span>\n");
      out.write("                          <a ><?php echo $row['course_name']?></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"media-right text-center\">\n");
      out.write("                        <div class=\"text-display-12\"><?php echo $row['quiz_obj_type']?></div>\n");
      out.write("                      </div>\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("\t\t\t\t             <?php\n");
      out.write("\t\t\t\t   }\n");
      out.write("\t\t\t\t   $row_count++;\n");
      out.write("\t\t\t\t   }\n");
      out.write("\t  \n");
      out.write("\t  \n");
      out.write(" ?>\n");
      out.write("                  <div class=\"panel-footer\">\n");
      out.write("                    <a href=\"quizcourseview.php?tid=<?php echo $Login_id?>\" class=\"btn btn-success paper-shadow relative\" data-z=\"0\" data-hover-z=\"1\" data-animated > Check History</a>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\t\t\t  \t\t\t\t\t\t            \n");
      out.write("\t   \n");
      out.write("                      </tbody>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("                    </table>\n");
      out.write("                  </div>\n");
      out.write("\t\t\t\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\t\t\t  \n");
      out.write("     <div class=\"item col-xs-12 col-lg-6\" style =\"background-color: white;\">\n");
      out.write("\t \t   <h4 class=\"text-headline margin-none\">Forum Activity</h4>\n");
      out.write("\t\t   \n");
      out.write("                <p class=\"text-subhead text-light\">Latest forum topics & comments</p>\n");
      out.write("\t\t\t\t\n");
      out.write("\t      <ul class=\"list-group relative paper-shadow\" data-hover-z=\"0.5\" data-animated>\n");
      out.write("\t\t  \t  \n");
      out.write("\t\t  \t                           <li class=\"list-group-item paper-shadows\">\n");
      out.write("                    <div class=\"media v-middle\">\n");
      out.write("                      <div class=\"media-left\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                          <img src=\"images/<?php echo $row['user_pic']?>\" alt=\"person\" class=\"img-circle width-40\" />\n");
      out.write("                        </a>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"media-body\">\n");
      out.write("                        <a href=\"forumdetail.php?uid=<?php echo $Login_id?>&utype=<?php echo 'teacher'?>&username=<?php echo $row['forum_postby']?>&userpic=<?php echo $row['user_pic']?>&forumid=<?php echo  $row['forum_id']?>&screen=<?php echo 0 ?>\" class=\"text-subhead link-text-color\"><?php echo $row['forum_question']?></a>\n");
      out.write("                        <div class=\"text-light\">\n");
      out.write("                          Topic: <a><?php echo $row['forum_title']?></a> &nbsp; By: <a><?php echo $row['forum_postby']?></a>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                     <div class=\"media-right\">\n");
      out.write("                        <div class=\"width-60 text-right\">\n");
      out.write("\t\t\t\t\t                          <td><?php echo $date ?></td>\n");
      out.write("\n");
      out.write("                          \n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("                  </li> \n");
      out.write("\t\t\t  \t\t  \n");
      out.write("                </ul>\t\t\n");
      out.write("              </div>\n");
      out.write("\t\t\t  \n");
      out.write("        </div>\n");
      out.write("        <!-- /st-content-inner -->\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("        <!-- /st-content-inner -->\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <!-- /st-content -->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- /st-pusher -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    \n");
      out.write("    <footer class=\"footer\">\n");
      out.write("      <strong>QBMS</strong>  &copy; Copyright 2016\n");
      out.write("    </footer>\n");
      out.write("    <!-- // Footer -->\n");
      out.write("\n");
      out.write("  </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
