package org.questionBank.data;
// Generated Oct 30, 2016 1:32:51 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "Answer", catalog = "questionbank")
public class Answer implements java.io.Serializable {

	private Integer id;
	private Integer questionId;
	private String answerText;
	private String answerId;

	public Answer() {
	}

	public Answer(String answerId) {
		this.answerId = answerId;
	}

	public Answer(Integer questionId, String answerText, String answerId) {
		this.questionId = questionId;
		this.answerText = answerText;
		this.answerId = answerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "question_id")
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@Column(name = "answer_text", length = 200)
	public String getAnswerText() {
		return this.answerText;
	}

	public void setAnswerText(String answerText) {
		this.answerText = answerText;
	}

	@Column(name = "answer_id", nullable = false, length = 7)
	public String getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(String answerId) {
		this.answerId = answerId;
	}

}
