package org.questionBank.data;
// Generated Oct 9, 2016 11:50:10 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "Question", catalog = "questionbank")
public class Question implements java.io.Serializable {

	private String questionId;
	private Integer courseId;
	private String chapter;

	public Question() {
	}

	public Question(String questionId) {
		this.questionId = questionId;
	}

	public Question(String questionId, Integer courseId, String chapter) {
		this.questionId = questionId;
		this.courseId = courseId;
		this.chapter = chapter;
	}

	@Id

	@Column(name = "question_id", unique = true, nullable = false, length = 7)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

	@Column(name = "course_id")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "chapter", length = 7)
	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

}
