package org.questionBank.data;
// Generated Oct 30, 2016 4:26:32 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "Question", catalog = "questionbank")
public class Question implements java.io.Serializable {

	private Integer id;
	private Integer courseId;
	private String chapter;
	private String questionText;
	private String questionId;

	public Question() {
	}

	public Question(String questionId) {
		this.questionId = questionId;
	}

	public Question(Integer courseId, String chapter, String questionText, String questionId) {
		this.courseId = courseId;
		this.chapter = chapter;
		this.questionText = questionText;
		this.questionId = questionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "course_id")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "chapter", length = 7)
	public String getChapter() {
		return this.chapter;
	}

	public void setChapter(String chapter) {
		this.chapter = chapter;
	}

	@Column(name = "question_text", length = 256)
	public String getQuestionText() {
		return this.questionText;
	}

	public void setQuestionText(String questionText) {
		this.questionText = questionText;
	}

	@Column(name = "question_id", nullable = false, length = 7)
	public String getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(String questionId) {
		this.questionId = questionId;
	}

}
